# -*- coding: utf-8 -*-
"""AG001_Questão5_2021

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19q1Hc3qK5xGfUAnlkP2VZ0VIKQQgwNA5
"""

''' Gustavo Aguiar Paiva - GET - 9576
    AG001 2021 - Questão 5 '''

# c é igual ao resto da divisão do número de matrícula por 10
matricula = 9576
c = matricula % 10

# Importando as funções solve, Symbol, exp e sin da biblioteca sympy
from sympy import solve, Symbol, exp, sin

# Criando a função 1
def minhaFuncao1(x):

  return exp(x-3) + exp(x-1) + exp(x) - c - 1

# Criando a função 2
def minhaFuncao2(x):

  return (x**4) - (4 * x**3) + (3 * x) - c

# Criando a função 3
def minhaFuncao3(x):

  return 4 * sin((c + 1) * x) + 2

# Define x como uma variável
x = Symbol('x')

# Resultado da primeira equação
y = minhaFuncao1(x)
Resultado1 = solve(y)

print('\n Resultado da primeira equação: ')
print(Resultado1)

# Resultado da segunda equação
w = minhaFuncao2(x)
Resultado2 = solve(w)

print('\n Resultado da segunda equação: ')
print(Resultado2)

# Resultado da terceira equação
g = minhaFuncao3(x)
Resultado3 = solve(g)

print('\n Resultado da terceira equação: ')
print(Resultado3)